name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - run: 'echo TZ: $TZ'
    - run: 'date'
    - name: make s
      run: make s
    - name: make test
      run: make test
