name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - macos-15
          - macos-14
          - macos-13
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - name: make s
      run: make s
    - name: make test
      run: make test
  build-freebsd:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      name: start freebsd
    - name: make s
      shell: freebsd {0}
      run: |
        cd ${GITHUB_WORKSPACE}
        make -d s
    - name: make test
      shell: freebsd {0}
      run: |
        cd ${GITHUB_WORKSPACE}
        make -d test
  build-windows:
    runs-on: ${{ matrix.platform.tag }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - tag: windows-2025
            expected_output: Windows
            cc: cc
          - tag: windows-2022
            expected_output: Windows
            cc: gcc
          - tag: windows-2019
            expected_output: Windows-2019
            cc: gcc
          - tag: windows-11-arm
            expected_output: Windows
            cc: gcc
    env:
      TZ: America/New_York
      EXT: .exe
      CC: ${{ matrix.platform.cc }}
      EXPECTED_OUTPUT: t/expected_output-${{ matrix.platform.expected_output }}.txt
    steps:
    - uses: actions/checkout@v4
    - name: make s.exe
      shell: bash
      run: make s.exe
    - name: make test
      shell: bash
      run: make test
