name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - macos-15
          - macos-14
          - macos-13
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - name: make s
      run: make s
    - name: make test
      run: make test
  build-freebsd:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      name: start freebsd
    - name: make s
      shell: freebsd {0}
      run: |
        pwd
        ls -la
        cd ${GITHUB_WORKSPACE}
        pwd
        ls -la
        cat Makefile
        make s
    - name: make test
      shell: freebsd {0}
      run: |
        pwd
        ls -la
        make test
  build-windows:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-2025
          - windows-2022
          - windows-2019
          - windows-11-arm
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - name: debug
      shell: bash
      run: |
        ls -la "C:\Program Files\Microsoft Visual Studio"
        which cc
    - name: make s
      shell: cmd
      run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && cc -o s s.c'
    - name: make test
      shell: bash
      run: |
        ./s > t/actual_output.txt
        diff -u t/expected_output-Windows.txt t/actual_output.txt
