name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - macos-15
          - macos-14
          - macos-13
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - name: make s
      run: make s
    - name: make test
      run: make test
  build-freebsd:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      name: start freebsd
    - name: make s
      run: make s
    - name: make test
      run: make test
  build-windows:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-2025
          - windows-2022
          - windows-2019
          - windows-11-arm
    env:
      TZ: America/New_York
    steps:
    - uses: actions/checkout@v4
    - name: nmake s
      shell: cmd
      run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && nmake s'
    - name: nmake test
      shell: cmd
      run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && nmake test'
